apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-conf
  labels:
    name: grafana-datasource-conf
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: 'http://prom-pod:9090'
