apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: lw-pod
  labels:
    name: lw-pod
spec:
  replicas: 20
  selector:
    matchLabels:
      app: lw-pod
  template:
    metadata:
      labels:
        app: lw-pod
    spec:
      containers:
        - name: lw-prod
          image: gcr.io/[PROJECT_ID]/locust-tasks:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_HOST
              value: lm-pod
            - name: TARGET_HOST
              value: dashboard
            - name: LOCUST_STEP
              value: false
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: website-creds
                  key: username
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: website-creds
                  key: password
