apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: lw-pod
  labels:
    name: lw-pod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lw-pod
  template:
    metadata:
      labels:
        app: lw-pod
    spec:
      containers:
        - name: lw-prod
          image: gcr.io/[PROJECT_ID]/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_HOST
              value: lm-pod
            - name: TARGET_HOST
              value: foo
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: website-creds
                  key: username
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: website-creds
                  key: password
